version: '3'

services:
  php:
    # Build the Docker image using the Dockerfile in the current directory
    build: .
    # Set the working directory inside the container to where the application files are
    working_dir: /var/www/html
    # Map the container's port 9000 to the host machine's port 9000 (for PHP-FPM)
    ports:
      - "9000:9000"
    # Optionally, add any environment variables if required
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=liberatube_db
    # Link the MySQL service to this service
    depends_on:
      - db

  db:
    # Use the official MySQL Docker image
    image: mysql:5.7
    # Set the MySQL root password and create a new database
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=liberatube_db
    # Optionally, you can mount a volume to persist data (e.g., database files) outside the container
    # volumes:
    #   - mysql_data:/var/lib/mysql

  webserver:
    # Use the official Nginx image
    image: nginx:latest
    # Map the container's port 80 to the host machine's port 80 (for Nginx)
    ports:
      - "80:80"
    # Link the PHP-FPM service to this service
    depends_on:
      - php
    # Mount the Nginx configuration directory
    volumes:
      - ./nginx:/etc/nginx/sites-available


