version: '3'
services:
  liberatube:
    build: .          
    ports:
      - "3000:3000"   
    depends_on:
      - db           

  db:
    image: mysql:5.7  
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_mysql_database_name
      MYSQL_USER: your_mysql_username
      MYSQL_PASSWORD: your_mysql_user_password
    volumes:
      - db_data:/var/lib/mysql 

volumes:
  db_data:
