name: Bug report
description: Found a bug? Share it here.
title: "[Bug] <>"
assignees: 
  - GoldDominik893
  
body:
  - type: dropdown
    id: where
    attributes:
      label: Where?
      options:
      - Stable
      - Beta
  
  - type: input
    id: version
    attributes:
      label: What version did you encounter this bug on?
      placeholder: "Example: v1.6"

  - type: textarea
    id: more-infos
    attributes:
      label: List the steps needed to reproduce this bug.
      placeholder: "Example: Go to settings, Set theme to light mode."
    validations:
      required: true
