name: Feature Request
description: Found a bug? Share it here.
title: "[Feature] <>"
assignees: 
  - GoldDominik893

body:
  - type: input
    id: url
    attributes:
      label: URL
      description: "the URL of your instance"
      placeholder: "Example: https://badyt.example.com"
    validations:
      required: true

  - type: input
    id: country
    attributes:
      label: Host country
      description: What country is the instance hosted in?
      placeholder: "Example: North Korea"
    validations:
      required: true

  - type: textarea
    id: more-infos
    attributes:
      label: Additional information
      description: "If you want to add other information on your instance, do so here:"
      placeholder: "Example: Our instance also has an .i2p URL, The source code changes are ..., etc."
    validations:
      required: false
