name: Feature Request
description: Have a feature request? Share it here.
title: "[Feature] <>"
assignees: 
  - GoldDominik893

body:
  - type: input
    id: feature
    attributes:
      label: Feature
      description: "What feature do you want to see on liberatube?"
      placeholder: "Example: add a custom video player"
    validations:
      required: true
      
  - type: textarea
    id: more-infos
    attributes:
      label: Additional information
      description: "If you want to add other information, like how to do it."
      placeholder: "Example: you can find the player at www.example.com."
    validations:
      required: false
